version: "3.9" 
services:  #to define the container
  php-apache:  #name of the service (can be any name you choose)
    image: php:8.1-apache  #specifies base image to be used for the container
    ports:
      - "8886:80"  #maps the port 8886 on the host machine to port 80 on the container
    volumes:
      - .:/var/www/html  #maps the current dir on the host machine to the directory inside the container (/var/www/html) - enables file sharing between host and container

#To run: http://localhost:8886